# Generated by Django 2.0.4 on 2018-04-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=20, unique=True)),
                ('class_name', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=5)),
                ('class_Teacher', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True)),
                ('relation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_Num', models.CharField(max_length=20, unique=True)),
                ('Name', models.CharField(max_length=150)),
                ('Address', models.CharField(default='', max_length=200)),
                ('parent_code', models.CharField(max_length=20)),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Class')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_Num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=500)),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Class')),
            ],
        ),
        migrations.AddField(
            model_name='subjectenroll',
            name='subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Subjects'),
        ),
        migrations.AddField(
            model_name='parents',
            name='Roll_Num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
