# Generated by Django 2.0.4 on 2018-04-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_Teacher',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
