# Generated by Django 2.0.4 on 2018-04-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20180405_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_Teacher',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
