# Generated by Django 2.0.4 on 2018-04-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20180405_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='class_code',
            new_name='class_name',
        ),
    ]
