# Generated by Django 2.0.3 on 2018-04-05 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20180405_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('class_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=5)),
                ('class_Teacher', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_Teacher',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_code',
        ),
        migrations.RemoveField(
            model_name='class',
            name='section',
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='class_name',
            field=models.ForeignKey(db_column='class_name', on_delete=django.db.models.deletion.DO_NOTHING, to='students.Class'),
        ),
        migrations.AddField(
            model_name='section',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Class'),
        ),
    ]
