# Generated by Django 2.0.3 on 2018-04-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20180406_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Section'),
        ),
    ]
