# Generated by Django 2.0.3 on 2018-04-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20180406_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
