# Generated by Django 2.0.3 on 2018-04-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20180406_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_code',
        ),
    ]
