# Generated by Django 2.0.3 on 2018-04-05 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20180406_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='Roll_Num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.Student'),
        ),
    ]
