# Generated by Django 2.0.3 on 2018-04-05 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20180406_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectenroll',
            name='Roll_Num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
