# Generated by Django 2.0.3 on 2018-04-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_is_fav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_fav',
            new_name='is_favorite',
        ),
    ]
